CREATE TABLE Tag (
    Id TINYINT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE Task_tag (
    TaskId BIGINT NOT NULL,
    TagId TINYINT NOT NULL,
    PRIMARY KEY (TaskId, TagId),
    CONSTRAINT FK_Task FOREIGN KEY(TaskId) REFERENCES task(id),
    CONSTRAINT FK_Tag FOREIGN KEY(TagId) REFERENCES Tag(Id)
);
GO