ALTER TABLE Tag ADD TagCategoryId TINYINT NOT NULL CONSTRAINT DF_Tag_TagCategoryId DEFAULT 1;
GO

ALTER TABLE Tag ADD CONSTRAINT FK_Tag_TagsCategory FOREIGN KEY (TagCategoryId) REFERENCES TagsCategory(Id);
GO